// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "yourThingID";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password


bool photoResistor0;
bool photoResistor1;
bool photoResistor2;
bool photoResistor3;
bool photoResistor4;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(photoResistor0, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(photoResistor1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(photoResistor2, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(photoResistor3, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(photoResistor4, READ, 1 * SECONDS, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
